FROM python:3.12-slim

ENV PYTHONDONTWRITEBYTECODE=1 \
    PYTHONUNBUFFERED=1

RUN apt-get update && apt-get install -y \
    build-essential \
    libpq-dev \
    curl \
    && rm -rf /var/lib/apt/lists/*

WORKDIR /app

COPY requirements/prod.txt requirements/prod.txt

RUN pip install --upgrade pip \
    && pip install --no-cache-dir -r requirements/prod.txt

COPY . .

CMD ["python3", "manage.py", "migrate"]
CMD ["gunicorn", "products.wsgi:application", "--bind", "0.0.0.0:8000"]